post-polls-filter
rewardz/Feeds pull request #153
Opened 2023-05-30 10:12 UTC by prashant-rewardz

2023-05-30 10:16 UTC, yatishTrootech requested changes

2023-05-30 10:16 UTC, yatishTrootech commented on feeds/views.py
>          post_polls = request.query_params.get("post_polls", None)
it will conflict with this flag

2023-05-30 10:22 UTC, prashant-rewardz commented on feeds/views.py
>          post_polls = request.query_params.get("post_polls", None)
No.
post_polls_filter is additional of post_polls flag.
Mobile have already integrated post_polls flag - to return Posts & Polls.
in new design, now user can filter out only Posts or only Polls.
to get that things, post_polls_filter flag is useful.

post_polls=1 -- return all Posts & Polls
post_polls=1 & post_polls_filter=post -- return only Posts
post_polls=1 & post_polls_filter=poll -- return only Polls

2023-05-30 10:38 UTC, prashant-rewardz commented on feeds/views.py
>          post_polls = request.query_params.get("post_polls", None)
No, that will not work.
because above condition will not fulfil requirements.

Requirements:
Greetings also consider as a Post
if filter is Post = Post + Greeting (only for version >=12)
if filter is Poll = Poll
if no filter = Post + Greeting (only for version >=12) + Poll

2023-05-31 04:52 UTC, yatishTrootech approved these changes

2023-05-31 15:55 UTC, merged