Ds/multi org without merge
rewardz/Feeds pull request #76
Opened 2022-09-09 09:56 UTC by dharmrdz

2022-09-15 10:02 UTC, rishireward commented on feeds/signals.py
> +
```suggestion
            feedback_post = post.feedbackpost_set.first()

```

2022-09-15 10:02 UTC, rishireward commented on feeds/tasks.py
> +    feedback_post = post.feedbackpost_set.all().first() if post else None
```suggestion
    feedback_post = post.feedbackpost_set.first() if post else None
```

2022-09-15 12:18 UTC, prashant-rewardz requested changes
there is some place in skor repo, where we are creating Post object with organization
https://github.com/rewardz/skor/blob/dev/profiles/api.py#L1516

that will fail if you merge multi-org feeds PR.

so, please raise PR in skor repo for above code, and merge both PR (skor and feeds repo) together.

2022-09-16 06:49 UTC, dharmrdz commented on feeds/models.py
> +    )
@rishireward , I am required to keep the same flow as post attachments and there are various validations which needs to be required to check for images and documents.

2022-09-16 07:13 UTC, dharmrdz commented on feeds/models.py
> +        return None
@rishireward , post can be multiple types. Before we get `feedback` post, we should check the post type i.e. feedback or not? If it's feedback type then only we need fetch from DB.

2022-09-20 07:23 UTC, rishireward commented on feeds/models.py
> +        return None
then you can do it like this so that we're not doing 2 queries
```suggestion
        if self.post and self.post.post_type == POST_TYPE.FEEDBACK_POST:
            feedbackpost = self.post.feedbackpost_set.first()
            return feedbackpost.feedback if feedbackpost else None
        return None
```

2022-09-21 05:09 UTC, rishireward approved these changes

2022-09-30 06:57 UTC, merged